### ISSUE TITLE
ac-brainstorm error

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#294] opened 2017-07-01 02:31 UTC
I20170630-21:25:48.744(-5)? Exception in callback of async function: TypeError: obj.data.forEach is not a function
I20170630-21:25:48.745(-5)?     at mergeFunction (/Users/ajp/dev/FROG/ac/ac-brainstorm/dist/index.js:34:14)
I20170630-21:25:48.746(-5)?     at server/mergeData.js:61:2
I20170630-21:25:48.747(-5)?     at runWithEnvironment (packages/meteor.js:1176:24)
I20170630-21:27:40.618(-5)? Exception in callback of async function: TypeError: obj.data.forEach is not a function
I20170630-21:27:40.620(-5)?     at mergeFunction (/Users/ajp/dev/FROG/ac/ac-brainstorm/dist/index.js:34:14)
I20170630-21:27:40.621(-5)?     at server/mergeData.js:61:2
I20170630-21:27:40.621(-5)?     at runWithEnvironment (packages/meteor.js:1176:24)
I20170630-21:27:50.274(-5)? Exception in callback of async function: TypeError: obj.data.forEach is not a function
I20170630-21:27:50.274(-5)?     at mergeFunction (/Users/ajp/dev/FROG/ac/ac-brainstorm/dist/index.js:34:14)
I20170630-21:27:50.274(-5)?     at server/mergeData.js:61:2
I20170630-21:27:50.275(-5)?     at runWithEnvironment (packages/meteor.js:1176:24)
I20170630-21:29:28.474(-5)? Exception in callback of async function: TypeError: obj.data.forEach is not a function
I20170630-21:29:28.475(-5)?     at mergeFunction (/Users/ajp/dev/FROG/ac/ac-brainstorm/dist/index.js:34:14)
I20170630-21:29:28.476(-5)?     at server/mergeData.js:61:2
I20170630-21:29:28.476(-5)?     at runWithEnvironment (packages/meteor.js:1176:24)
I20170630-21:29:28.478(-5)? Exception in callback of async function: TypeError: obj.data.forEach is not a function
I20170630-21:29:28.479(-5)?     at mergeFunction (/Users/ajp/dev/FROG/ac/ac-brainstorm/dist/index.js:34:14)
I20170630-21:29:28.480(-5)?     at server/mergeData.js:61:2
I20170630-21:29:28.480(-5)?     at runWithEnvironment (packages/meteor.js:1176:24)
I20170630-21:29:28.483(-5)? Exception in callback of async function: TypeError: obj.data.forEach is not a function
I20170630-21:29:28.484(-5)?     at mergeFunction (/Users/ajp/dev/FROG/ac/ac-brainstorm/dist/index.js:34:14)
I20170630-21:29:28.485(-5)?     at server/mergeData.js:61:2

**Comment by houshuang** [comment] 2017-07-01 08:30
This is almost certainly not a bug in the core code, but a mismatch in inputs and outputs in the graph - impossible to say without seeing your full graph. Ie. you have an invalid graph.

This is one of our main priorities in the next few months - making it much easier to generate correct graphs, and impossible to run incorrect graphs. You'll see a few issues around this. There are some elements that are very easy (but still needs doing, testing, UI etc), and some that are more complex - basically entail implementing our own type system. It's fairly easy to say that one activity produces a list of objects with title and content keys, but what when you have a generic operator which takes a list and distributes four random elements to each group? Can you trace the types through the operator, to know that the output will be a list of four objects with keys title and content? 

In the meantime, you basically need to know which elements work together. However, the teacher view is quite useful - you can click on any activity/operator to see the input/output data structures. (You can also use Robomongo or something similar to directly inspect the database at port 3001, all the products, objects, etc are stored permanently). 

I'm going to close this bug, feel free to reopen if you cannot figure out the error, and attach the graph you ran.

**Closed** 2017-07-01 08:34 UTC
