### ISSUE TITLE
Error: Cannot find module 'sharedb' (critical)

### ISSUE THREAD

**Issue by aperritano** [chili-epfl/FROG#299] opened 2017-07-02 01:33 UTC
Here are the steps to reproduce this:

**1. created a new activity
2. in ac-ck-student folder**

npm install --save material-ui
npm install --save react-tap-event-plugin

**3. Meteor complained:**

20170701-20:15:55.377(-5)? (STDERR) in the root directory of your application.
W20170701-20:15:55.581(-5)? (STDERR) /Users/ajp/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170701-20:15:55.581(-5)? (STDERR) 						throw(ex);
W20170701-20:15:55.582(-5)? (STDERR) 						^
W20170701-20:15:55.582(-5)? (STDERR) 
W20170701-20:15:55.583(-5)? (STDERR) Error: Cannot find module 'sharedb'
W20170701-20:15:55.583(-5)? (STDERR)     at Function.Module._resolveFilename (module.js:325:15)
W20170701-20:15:55.584(-5)? (STDERR)     at Function.Module._load (module.js:276:25)
W20170701-20:15:55.584(-5)? (STDERR)     at Module.require (module.js:353:17)
W20170701-20:15:55.585(-5)? (STDERR)     at require (internal/module.js:12:17)
W20170701-20:15:55.585(-5)? (STDERR)     at Object.<anonymous> (/Users/ajp/dev/FROG/frog-utils/dist/generateReactiveFn.js:12:16)
W20170701-20:15:55.586(-5)? (STDERR)     at Module._compile (module.js:409:26)
W20170701-20:15:55.587(-5)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170701-20:15:55.587(-5)? (STDERR)     at Module.load (module.js:343:32)
W20170701-20:15:55.587(-5)? (STDERR)     at Function.Module._load (module.js:300:12)
W20170701-20:15:55.588(-5)? (STDERR)     at Module.require (module.js:353:17)
W20170701-20:15:55.588(-5)? (STDERR)     at require (internal/module.js:12:17)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.
=> Modified -- restarting.
                                              
Unable to resolve some modules:

  "recompose" in                              
/Users/ajp/dev/FROG/frog/node_modules/op-distribute/node_modules/frog-utils/dist/index.js
(web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save recompose         
                                              
                                              
Unable to resolve some modules:

  "recompose" in /Users/ajp/dev/FROG/frog/node_modules/frog-utils/dist/index.js
(os.osx.x86_64)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save recompose       

**4. shut down meteor and do: meteor npm install --save recompose**  
**5. finished with this output:**

npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/electron-download/node_modules/fs-extra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/flow-copy-source/node_modules/yargs/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/flow-typed/node_modules/yargs/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/frog-utils/node_modules/react-dom/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/unzip/node_modules/fstream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/electron-download/node_modules/fs-extra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/flow-copy-source/node_modules/yargs/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/flow-typed/node_modules/yargs/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/frog-utils/node_modules/react-dom/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/unzip/node_modules/fstream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/unzip/node_modules/fstream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/electron-download/node_modules/fs-extra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/flow-copy-source/node_modules/yargs/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/flow-typed/node_modules/yargs/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/frog-utils/node_modules/react-dom/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/unzip/node_modules/fstream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/electron-download/node_modules/fs-extra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/flow-copy-source/node_modules/yargs/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/flow-typed/node_modules/yargs/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/frog-utils/node_modules/react-dom/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/unzip/node_modules/fstream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/electron-download/node_modules/fs-extra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/flow-copy-source/node_modules/yargs/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/flow-typed/node_modules/yargs/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/frog-utils/node_modules/react-dom/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/unzip/node_modules/fstream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/electron-download/node_modules/fs-extra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/flow-copy-source/node_modules/yargs/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/flow-typed/node_modules/yargs/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/frog-utils/node_modules/react-dom/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/unzip/node_modules/fstream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/electron-download/node_modules/fs-extra/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/flow-copy-source/node_modules/yargs/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/flow-typed/node_modules/yargs/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/frog-utils/node_modules/react-dom/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/unzip/node_modules/fstream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/unzip/node_modules/fstream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/unzip/node_modules/fstream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/unzip/node_modules/fstream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/unzip/node_modules/fstream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/unzip/node_modules/fstream/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/Users/ajp/dev/FROG/node_modules/unzip/node_modules/fstr

**5. Start meteor again:**

> meteor
[[[[[ ~/dev/FROG/frog ]]]]]                   

=> Started proxy.                             
=> Started MongoDB.                           
W20170701-20:24:58.598(-5)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20170701-20:24:58.646(-5)? (STDERR) While this implementation will work correctly, it is known to be
W20170701-20:24:58.646(-5)? (STDERR) approximately three times slower than the native implementation.
W20170701-20:24:58.647(-5)? (STDERR) In order to use the native implementation instead, run
W20170701-20:24:58.647(-5)? (STDERR) 
W20170701-20:24:58.648(-5)? (STDERR)   meteor npm install --save bcrypt
W20170701-20:24:58.648(-5)? (STDERR) 
W20170701-20:24:58.648(-5)? (STDERR) in the root directory of your application.
W20170701-20:24:58.649(-5)? (STDERR) /Users/aperritano/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170701-20:24:58.649(-5)? (STDERR) 						throw(ex);
W20170701-20:24:58.649(-5)? (STDERR) 						^
W20170701-20:24:58.650(-5)? (STDERR) 
W20170701-20:24:58.650(-5)? (STDERR) Error: Cannot find module 'sharedb'
W20170701-20:24:58.651(-5)? (STDERR)     at Function.Module._resolveFilename (module.js:325:15)
W20170701-20:24:58.651(-5)? (STDERR)     at Function.Module._load (module.js:276:25)
W20170701-20:24:58.651(-5)? (STDERR)     at Module.require (module.js:353:17)
W20170701-20:24:58.651(-5)? (STDERR)     at require (internal/module.js:12:17)
W20170701-20:24:58.652(-5)? (STDERR)     at Object.<anonymous> (/Users/aperritano/dev/FROG/frog-utils/dist/generateReactiveFn.js:12:16)
W20170701-20:24:58.652(-5)? (STDERR)     at Module._compile (module.js:409:26)
W20170701-20:24:58.652(-5)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170701-20:24:58.653(-5)? (STDERR)     at Module.load (module.js:343:32)
W20170701-20:24:58.653(-5)? (STDERR)     at Function.Module._load (module.js:300:12)
W20170701-20:24:58.653(-5)? (STDERR)     at Module.require (module.js:353:17)
W20170701-20:24:58.653(-5)? (STDERR)     at require (internal/module.js:12:17)
=> Exited with code: 1
W20170701-20:25:01.722(-5)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20170701-20:25:01.723(-5)? (STDERR) While this implementation will work correctly, it is known to be
W20170701-20:25:01.723(-5)? (STDERR) approximately three times slower than the native implementation.
W20170701-20:25:01.724(-5)? (STDERR) In order to use the native implementation instead, run
W20170701-20:25:01.724(-5)? (STDERR) 
W20170701-20:25:01.724(-5)? (STDERR)   meteor npm install --save bcrypt
W20170701-20:25:01.725(-5)? (STDERR) 
W20170701-20:25:01.725(-5)? (STDERR) in the root directory of your application.
W20170701-20:25:01.932(-5)? (STDERR) /Users/aperritano/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170701-20:25:01.934(-5)? (STDERR) 						throw(ex);
W20170701-20:25:01.934(-5)? (STDERR) 						^
W20170701-20:25:01.934(-5)? (STDERR) 
W20170701-20:25:01.935(-5)? (STDERR) Error: Cannot find module 'sharedb'
W20170701-20:25:01.935(-5)? (STDERR)     at Function.Module._resolveFilename (module.js:325:15)
W20170701-20:25:01.935(-5)? (STDERR)     at Function.Module._load (module.js:276:25)
W20170701-20:25:01.936(-5)? (STDERR)     at Module.require (module.js:353:17)
W20170701-20:25:01.936(-5)? (STDERR)     at require (internal/module.js:12:17)
W20170701-20:25:01.936(-5)? (STDERR)     at Object.<anonymous> (/Users/aperritano/dev/FROG/frog-utils/dist/generateReactiveFn.js:12:16)
W20170701-20:25:01.936(-5)? (STDERR)     at Module._compile (module.js:409:26)
W20170701-20:25:01.937(-5)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170701-20:25:01.937(-5)? (STDERR)     at Module.load (module.js:343:32)
W20170701-20:25:01.937(-5)? (STDERR)     at Function.Module._load (module.js:300:12)
W20170701-20:25:01.937(-5)? (STDERR)     at Module.require (module.js:353:17)
W20170701-20:25:01.938(-5)? (STDERR)     at require (internal/module.js:12:17)
=> Exited with code: 1
W20170701-20:25:04.555(-5)? (STDERR) Note: you are using a pure-JavaScript implementation of bcrypt.
W20170701-20:25:04.556(-5)? (STDERR) While this implementation will work correctly, it is known to be
W20170701-20:25:04.556(-5)? (STDERR) approximately three times slower than the native implementation.
W20170701-20:25:04.556(-5)? (STDERR) In order to use the native implementation instead, run
W20170701-20:25:04.557(-5)? (STDERR) 
W20170701-20:25:04.557(-5)? (STDERR)   meteor npm install --save bcrypt
W20170701-20:25:04.557(-5)? (STDERR) 
W20170701-20:25:04.558(-5)? (STDERR) in the root directory of your application.
W20170701-20:25:04.755(-5)? (STDERR) /Users/aperritano/.meteor/packages/meteor-tool/.1.5.0.edxpxb++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:280
W20170701-20:25:04.755(-5)? (STDERR) 						throw(ex);
W20170701-20:25:04.756(-5)? (STDERR) 						^
W20170701-20:25:04.756(-5)? (STDERR) 
W20170701-20:25:04.756(-5)? (STDERR) Error: Cannot find module 'sharedb'
W20170701-20:25:04.757(-5)? (STDERR)     at Function.Module._resolveFilename (module.js:325:15)
W20170701-20:25:04.757(-5)? (STDERR)     at Function.Module._load (module.js:276:25)
W20170701-20:25:04.758(-5)? (STDERR)     at Module.require (module.js:353:17)
W20170701-20:25:04.759(-5)? (STDERR)     at require (internal/module.js:12:17)
W20170701-20:25:04.759(-5)? (STDERR)     at Object.<anonymous> (/Users/aperritano/dev/FROG/frog-utils/dist/generateReactiveFn.js:12:16)
W20170701-20:25:04.760(-5)? (STDERR)     at Module._compile (module.js:409:26)
W20170701-20:25:04.760(-5)? (STDERR)     at Object.Module._extensions..js (module.js:416:10)
W20170701-20:25:04.760(-5)? (STDERR)     at Module.load (module.js:343:32)
W20170701-20:25:04.761(-5)? (STDERR)     at Function.Module._load (module.js:300:12)
W20170701-20:25:04.761(-5)? (STDERR)     at Module.require (module.js:353:17)
W20170701-20:25:04.761(-5)? (STDERR)     at require (internal/module.js:12:17)
=> Exited with code: 1
=> Your application is crashing. Waiting for file change.

seems recompose blew away the frog-utils node_modules 
how to regenerate them? 

is it connected to this issue?
[https://stackoverflow.com/questions/40585266/meteor-cannot-find-re-exported-module](https://stackoverflow.com/questions/40585266/meteor-cannot-find-re-exported-module)
Possibly this one this? 
[https://github.com/meteor/meteor/issues/7302](https://github.com/meteor/meteor/issues/7302)
suggestions for moving forward?

**Comment by houshuang** [comment] 2017-07-02 07:04
This is weird - seems like your whole setup is ruined, with tons of dependencies missing all over the place. All of these should have been brought in by initial_Setup. Are you positive that Meteor worked properly before you created the new activity? createActivity should not affect any other package/activity...

**Comment by aperritano** [comment] 2017-07-02 23:47
Yes, meteor and the system was working flawlessly before.

I was able to fix this by doing git clean -fdx and rerunning ./initial_setup.sh. However the steps in this issue are still reproducible.

**Comment by houshuang** [comment] 2017-07-03 07:00
To my surprise, can confirm that this happens following only the steps mentioned in the first post. Not sure why createActivity would cause that. It seems like the local dependencies of frog/frog are not installed in frog/frog/node_modules anymore.

**Comment by lfaucon** [comment] 2017-07-04 11:58
@aperritano , @houshuang Apparently the bug does not come from `createActivities.js`. I can reproduce the same bug with only the following steps:

1. `git clone ... && ./initial_setup.sh`
2. `cd frog && meteor`
3. `cd ac/ac-chat && npm install --save react-player`

At that point meteor crashes with same error message as apperitano mentioned above

I keep working on fixing this.

**Comment by houshuang** [comment] 2017-07-04 12:34
Weird. Does it matter in which package you install react-player?

**Comment by lfaucon** [comment] 2017-07-04 15:56
No the package does not matter

This issue is exactly what is happening to us:
https://github.com/npm/npm/issues/10343 

## Observations
After trying to find a fix or a workaround for quite a long time, I found that:
- `yarn` and `npm` have different behaviour concerning symlinked files non listed in the dependencies
- adding `frog-utils: "*"` in the dependencies of each ac-.. and op-.. would fix it, but all the installations with yarn fail as yarn cannot find the dependency
- `yarn link` does not work

## Suggestions 
### Best option:
Not running npm install in the ac/op packages. Instead using `yarn add` and `yarn install`. Would be nice to have a way to disallow the use of npm install. I don't know if that exists.

### Other option:
Giving up on `yarn` and using only `npm`, thus applying the fix of adding `frog-utils: "*"` in the dependencies.

**Comment by houshuang** [comment] 2017-07-04 16:22
Thanks @lfaucon for your great investigative work. I think the reason I've never encountered this, is because on my system, npm is really slow, so I always run yarn when I can (in ac/op/frog-utils). I think that switching back to npm right now would slow down our entire setup (including CI etc) a huge amount. 

I think these kinds of issues are recognized by both npm and yarn, since more and more people are doing complex mono-repos etc, so they might get addressed.

I suggest that for now, we continue using yarn outside frog/frog, and meteor npm install in frog/frog. We can inform about this, and given that blowing away with `git clean -fdx; _initial_setup.sh` is always an option, I don't think the situation is too bad.

The new npm (v. 5) is supposed to be significantly faster, also use lockfile by default etc, however Meteor does not yet support it. Once Meteor supports it, we can re-investigate, and consider standardizing on npm 5 for everything. 

Closing as resolved. Will update README.

**Closed by houshuang** 2017-07-04 16:22 UTC
Labels: bug
